spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TicketCenter
    username: postgres
    password: Kyuubi279
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl_auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
        database: postgres
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    server:
      port: 8081
      address: 192.168.91.202